# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b28a0ba2df8cee4ba83e078f8398a1535c6389888a5e0db2cf5451319d61d6396df00684e48d6a4df97afc2d2814f5f9dd270f06608d100346be6bfae08d8fda

test:
  secret_key_base: bbc4de37164ba4ff9bfc5e1ac8c4dbd3b2330a293e3cdfd0d36e07953adf03be1f07b5736a4588752e3154f8595bb95c1e16efc595c2b7d6597ea0795167b90d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
