# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ceb215841e4c07a834ce75b32460fa2bceb47d559570cddcf1484dae5e1365cf7783b0f4fc38d7c4070be6835c2776c737b2229f34b4182e662f164af2be05a

test:
  secret_key_base: 4185665702af12e00fb9069570676cce113ea7062496b32e569e6a79220df74a56dae45135e23a88100cdd85996cfdaf15a5b0ed2cd84b954a38191aabccc823

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
