development:
  clients:
    default:
      database: dummy_api_development
      hosts:
        - localhost:27017
      options:
test:
  clients:
    default:
      database: dummy_api_test
      hosts:
        - localhost:27017
      options:
        read:
          mode: :primary
        max_pool_size: 1
